"""Project-wide constants."""

APP_NAME = "unclaw"
DISPLAY_NAME = "Unclaw"

CONFIG_DIRECTORY_NAME = "config"
PROMPTS_DIRECTORY_NAME = "prompts"
DATA_DIRECTORY_NAME = "data"
LOGS_DIRECTORY_NAME = "logs"
SESSIONS_DIRECTORY_NAME = "sessions"
CACHE_DIRECTORY_NAME = "cache"
FILES_DIRECTORY_NAME = "files"

APP_CONFIG_FILE_NAME = "app.yaml"
MODELS_CONFIG_FILE_NAME = "models.yaml"
SYSTEM_PROMPT_FILE_NAME = "system.txt"
DATABASE_FILE_NAME = "memory/app.db"
LOG_FILE_NAME = "runtime.log"

PROJECT_ROOT_ENV_VAR = "UNCLAW_PROJECT_ROOT"

# Runtime and provider defaults.
DEFAULT_CONTEXT_HISTORY_MESSAGE_LIMIT = 20
DEFAULT_CONTEXT_HISTORY_CHAR_BUDGET = 24_000
DEFAULT_RUNTIME_AGENT_STEP_LIMIT = 6
DEFAULT_RUNTIME_TOOL_TIMEOUT_SECONDS = 15.0
DEFAULT_RUNTIME_TOOL_CALL_LIMIT = 8
RUNTIME_TOOL_RESULT_POLL_INTERVAL_SECONDS = 0.01
DEFAULT_OLLAMA_REQUEST_TIMEOUT_SECONDS = 60.0

# Startup diagnostics.
DEFAULT_LOG_RETENTION_DAYS = 30
OLLAMA_STARTUP_INSPECTION_TIMEOUT_SECONDS = 1.5
OLLAMA_STARTUP_WAIT_TIMEOUT_SECONDS = 8.0
OLLAMA_STARTUP_POLL_INTERVAL_SECONDS = 0.5
OLLAMA_STARTUP_RECHECK_TIMEOUT_SECONDS = 1.0

# Telegram runtime policy.
TELEGRAM_MESSAGE_CHARACTER_LIMIT = 4000
TELEGRAM_POLL_RETRY_DELAY_SECONDS = 3.0
TELEGRAM_PENDING_MESSAGE_LIMIT_PER_CHAT = 2
TELEGRAM_PENDING_UPDATE_WAIT_INTERVAL_SECONDS = 0.01
TELEGRAM_REJECTED_CHAT_LOOKBACK_LIMIT = 20

# Session memory and summary limits.
DEFAULT_SESSION_MEMORY_SNIPPET_LIMIT = 3
SESSION_MEMORY_SNIPPET_CHARACTER_LIMIT = 90
SESSION_SUMMARY_INTENT_LIMIT = 3
SESSION_SUMMARY_INTENT_CHARACTER_LIMIT = 80
SESSION_SUMMARY_REPLY_CHARACTER_LIMIT = 120
SESSION_SUMMARY_RETAINED_FACT_LIMIT = 3
SESSION_SUMMARY_RETAINED_UNCERTAINTY_LIMIT = 2
SESSION_SUMMARY_FINDING_CHARACTER_LIMIT = 120

# External skills catalog.
DEFAULT_SKILLS_CATALOG_URL = (
    "https://raw.githubusercontent.com/unclaw-ai/skills/main/catalog.json"
)

# Fallback reply strings shared between runtime.py and research_flow.py.
EMPTY_RESPONSE_REPLY = "The local model returned an empty response."
RUNTIME_ERROR_REPLY = (
    "I could not complete that request locally right now. "
    "Check that Ollama is running and the selected model is available."
)
